### ISSUE TITLE
Add support for Polymer 2

### ISSUE THREAD

**Issue by herkulano** [platosha/angular-polymer#100]
With Polymer 2 in beta it would be great to start working with it along with Angular 2.

**Comment by samiheikki** [comment]
Hi @herkulano and thanks for your interest.

Polymer 2.0 is still in Alpha-preview and not recommended for production. So for the time being, we are not upgrading this to work with 2.0. But there is a possibility that after Polymer 2.0 becomes more stable (beta/RC/stable) we'll upgrade this package also. But nothing yet in our roadmap.

For future readers, please 👍 (+1) this issue if you feel that we should add support for Polymer 2.0.

**Comment by clydin** [comment]
This may need to be accelerated.  Angular 2.2+ direct renders to the DOM now.  The trick of modifying the DomAdapter doesn't seem to work.
One of Polymer 2.0's big improvements is the elimination of the need for `Polymer.dom`.

**Comment by samiheikki** [comment]
@clydin I confirm the problem with Angular 2.2.0. Created a new issue for it #104 and will be the next we'll be working on.
