### ISSUE TITLE
Failed to load resource: .../iron-component-page/iron-component-page.html

### ISSUE THREAD

**Issue by ybarbaria** [platosha/angular-polymer#102]
Hello, 

I have this error in both browser, but with IE,Edge and firefox, this error break my app angular2. 
This error apear on my application since I use your component vaadin. 
But works with chrome. 
I have any solution? 
Thx 

Yvan 

![errorironcomp](https://cloud.githubusercontent.com/assets/5574663/19525432/3490a898-9621-11e6-8292-9b4bdb6d38de.PNG)

**Comment by platosha** [comment]
I believe you can install this element with bower:

```
$ bower install PolymerElements/iron-component-page
```

But seriously, normally it should not be required. It’s an element that renders documentation pages for Polymer elements, probably not directly useful for your app.

Please try to find, what tries to load it. Looking for a `Referrer` header for the request of `iron-component-page` in the network log inside browser developer tools might help.

**Comment by ybarbaria** [comment]
Hello @platosha,

Yesterday, I have installed icon-component and was worst, 

I find the referrers : 

`<link rel="import" href="../iron-component-page/iron-component-page.html">`

inside index.html from vaadin-data-picker, vaadin-combo-box ...

**Comment by ybarbaria** [comment]
@platosha 
My mistake, i have imported  `<link rel="import" href="lib/paper-button/index.html" />`  instead of `<link rel="import" href="lib/paper-button/paper-button.html" />`

Sorry for the distrub ! 
thx again
