### ISSUE TITLE
ANGULAR-CLI 1.0.0-beta.20-4

### ISSUE THREAD

**Issue by niveo** [platosha/angular-polymer#105]
Prefix, sufix and other things don't work with CLI 1.0.0-beta.20-4...
any idea whay?

`<paper-input label="Usuário"><iron-icon icon="user" prefix></iron-icon></paper-input>`

![image](https://cloud.githubusercontent.com/assets/5286878/20392103/86efb8b0-acbd-11e6-97fb-0ed25d437b28.png)

thanks...

**Comment by rstpv** [comment]
Probably related to #104 
The angular dependency in the cli beta.20-4 Angular dependency is: "@angular/core": "^2.1.0",

**Comment by niveo** [comment]
works thanks

**Comment by platosha** [comment]
The same issue as #104. See that for more information.
