### ISSUE TITLE
How to reference images

### ISSUE THREAD

**Issue by BorntraegerMarc** [platosha/angular-polymer#112]
Hi guys

I've posted this question: https://stackoverflow.com/questions/41016503/angular2-vaadin-angular2-polymer-how-to-reference-images

Because I was not sure, if I should submit this here... I'm quite the noobie with webpack. Would be incredible useful if somebody could solve my problem :)

Cheers,
Marc

**Comment by tomivirkki** [comment]
Hello @BorntraegerMarc 

The syntax in your example at least looks ok `<paper-card image="img/home.jpg">`
So as long as the `<paper-card>` element gets properly upgraded this should work as expected.
Does your import of 'paper-input.html' work fine?

**Comment by BorntraegerMarc** [comment]
Thanks for the answer @tomivirkki . Yeah I'm 100% sure that the import works.

Don't you think there is rather an error with webpack? Because I can't find the file, when I'm searching for it in the dev tools in the browser?

**Comment by platosha** [comment]
@BorntraegerMarc I am pretty sure this is not related with Angular or our library, closing this. Please see my hints for your webpack setup on SO.

**Comment by BorntraegerMarc** [comment]
You are correct @platosha  -> this has nothing to do with Angular or vaadin lib. But I was not sure, where to start searching... But thank you very much for your answer. I'll continue the discussion over there. Would be glad, if you could answer to my comment :)
