### ISSUE TITLE
Best practices & how to combine angular form validators with polymer inputs

### ISSUE THREAD

**Issue by BorntraegerMarc** [platosha/angular-polymer#113]
Hi there

I have the following form:
```
<form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
     <div class="form-group">
        <paper-input
                label="Username"
                type="text"
                id="username"
                class="form-control"
                formControlName="username"
                name="username"></paper-input>
    </div>
</form>
```

And the following TS script to it:
```
this.registerForm = new FormGroup({
  username: new FormControl(null, Validators.required)
})
```

How should I set up the paper-input to use the angular validation? Or do I always need to include validations twice? With `required` in the html template?

To specify my question a little bit:
I have for example a service call like this:
```
    onSubmit() {
        this.authService.register(new User(
            this.registerForm.value.username
        )).subscribe(
            data => {
                alert('Successfully registered');
                this.router.navigateByUrl('/auth/login');
            },
            (error: Error) => {
                switch (error.type) {
                    case 'username_invalid':
                        break;
                }
            }
        );
    }
```

Now I am not sure on how to set the username input invalid with the specific error message. Should I do this over angulars `FormGroup` and somehow configure it that it updates the polymer frontend automatically? Or should I set the invalid property directly on `paper-input`? What is the suggested best practice here?

**Comment by BorntraegerMarc** [comment]
Nobody? Harmless shutout to @samiheikki and @platosha :)

And I'm also talking about general topics (and best practices) like:

1. Should I use ngForm or iron-form?
2. How should polymer element methods be called? For example `validate()` on a `paper-input`
3. How do I display my `errorMessage` property when it is not empty in an `paper-input`. As this does not seem to work...

Any other best practices that I'm missing? Would be very happy for a feedback as it seems to me, that documentation for this part is missing... Or I'm missing it :)

**Comment by Chabane** [comment]
You can use a custom validator. It works for me.

See https://dzone.com/articles/custom-validators-in-template-driven-angular-2-for

**Comment by BorntraegerMarc** [comment]
@Chabane Thanks for the answer. I agree, they work for me as well. Did you somehow manage to display the updated errorMessage in an paper-input? As I'm struggling with that...

But I'm talking more about best practices rather then if something works :)

**Comment by BorntraegerMarc** [comment]
was solved with https://github.com/platosha/angular-polymer/commit/e1441562f86ad343fbea85b0bf1bf36cef5f8f2e
