### ISSUE TITLE
Questions about 1.0.0 release

### ISSUE THREAD

**Issue by Splaktar** [platosha/angular-polymer#116]
Based on RC1, RC2, and RC3 of 1.0.0 of this library coming out in the last 2 weeks, is the plan to release 1.0.0 using full Shadow DOM v0 and/or Angular 2.1.x or less?

I was surprised when I saw that this might be happening. But as I've thought about it, perhaps it makes sense to get a 1.0 out that works with Angular 2.0.0-2.1.x rather than re-architecting things during the RC phase (like Angular).

Would the [new "re-write"](https://github.com/vaadin/angular2-polymer/issues/104#issuecomment-267653606) be the main goal of 2.0?

However, I think that the primary `README.md` needs to be updated to call out these concerns (Performance with Shadow DOM v0 vs Angular version limitations) and the [demo should be updated](https://github.com/vaadin/angular2-polymer/commit/86632b0242a7e7bbc68bb0e40f76090b94f7c35b#commitcomment-20217974) before releasing a final 1.0.0 of angular2-polymer. Ideally the demo would have a full Shadow DOM v0 version and an Angular 2.1.x version for comparison.

Are there any other goals for the 1.0.0 release (which doesn't have a [milestone defined](https://github.com/vaadin/angular2-polymer/milestones))?

**Comment by platosha** [comment]
You’ve guessed it right.

The version 1.0.0 is now out. It supports for using either with full Shadow DOM v0 polyfill or with Angular <= v2.1.

Speaking about the future, I have some news to tell. Unfortunately, v1.0.0 was the last release by Vaadin for the `angular2-polymer` library. We, the Vaadin Elements team, are going to focus on the main team purpose: developing Vaadin Elements, a set of high-quality Polymer elements for business applications.

This does not mean the end, however. I am going to continue develop and maintain this library as a personal community-oriented project from now on.

Next, this project is going to be transferred and renamed. Then I will continue the “re-write” work on the issues #104 and #86, which are the biggest challenges right now. Stay tuned.

**Comment by Splaktar** [comment]
That's understandable. I'm very happy to see that you are going to continue to contribute to this on the side! Thank for you your efforts!

I'm going to go ahead and pull most of my current projects off of Polymer (using Angular Material2 and ngBootstrap instead). But I'll be happy to try Polymer out again on new projects in the future should this re-write/re-name ultimately be successful. Perhaps along with the beta/final of Polymer 2.0.

**Comment by MarkPieszak** [comment]
Sad to hear that @platosha but I'm also available to help get things going, so keep me in the loop! It must stay alive :)

**Comment by BorntraegerMarc** [comment]
@MarkPieszak and @Splaktar

If your willing to help us out:
https://github.com/platosha/angular-polymer/issues/123

We appreciate it :)

**Comment by Splaktar** [comment]
OK, I am following that issue now.
