### ISSUE TITLE
Disabling a paper-input doesn't seem to work

### ISSUE THREAD

**Issue by Chabane** [platosha/angular-polymer#117]
Hi,

Disabling a paper-input doesn't seem to work.

`<paper-input  label="username " formControlName="username" required [disabled]="usernameCache"></paper-input>`

`<paper-input  label="username " formControlName="username" required [readonly]="usernameCache"></paper-input>`

I tried to do : this.loginForm.controls['username'].disable(); same result.

Any idea?

**Comment by BorntraegerMarc** [comment]
@Chabane To disable the form from the angular way is not possible as far as I know. (at least at the moment)...

Could you try to use something like:
```
let loginForm: any = document.querySelector('#login-form');
loginForm.disable();
```

And this:
`<paper-input [disabled]="yourAngularBoolean"></paper-input>`
Should work
