### ISSUE TITLE
Angular2-polymer does not support this polymer 0.5.x version? 

### ISSUE THREAD

**Issue by 13842648081** [platosha/angular-polymer#118]
Hi，
I'm in the integrated angular2 and polymer,But when run my app I had a problem , 
--------------------------------------
**(index):66 Error: (SystemJS) Cannot read property 'useShadow' of undefined**
-------------------------------------
I am using polymer 0.5.2 version,
Perhaps Angular2-polymer does not support this polymer 0.5.x version? 

Thanks and Best Regards!

**Comment by platosha** [comment]
Hello, @13842648081 

yes, Polymer 0.5.x is not supported, and was actually never supported in `angular2-polymer` before. As for now, 0.5.2 is more than 2 years old.

Polymer v2.0 is under active development currently. It will use ES6 and the modern Web Components technology stack, that was agreed between multiple browser version. I would suggest to try it and upgrade when it is out.
