### ISSUE TITLE
Can't get angular2-polymer working on angular 2.3.1

### ISSUE THREAD

**Issue by yobud** [platosha/angular-polymer#119]
Hi! Thank you for your awesome work!

Registering polymer elements as show in the readme no longer works on angular 2.3.1, because no function call is allowed in NgModule declaration.

> ERROR in Error encountered resolving symbol values statically. Calling function 'PolymerElement', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

I absolutely don't know how to make angular2-polymer working again, as PolymerElement function does some complex stuff.

Thank you for your help,

Jérémy

**Comment by Chabane** [comment]
See the issue #104

**Comment by yobud** [comment]
Thank you, got it working by using shadow dom. Hope it'll not be too slow with polyfill.
