### ISSUE TITLE
Explain difference to angular-polymer repo

### ISSUE THREAD

**Issue by BorntraegerMarc** [platosha/angular-polymer#124]
Somewhere we need to display differences from this repo to https://github.com/platosha/angular-polymer

Where should that be and how are the two gonna live together?

In my view: there should only be one repo with different "beta" branches. Also in regard to angular naming convention: I think the repo should be named "angular-polymer". And not bound to a specific version number of angular

**Comment by BorntraegerMarc** [comment]
@platosha please give your input here. I can do merge requests based on your decision

**Comment by platosha** [comment]
@BorntraegerMarc agree.

`platosha/angular-polymer` is a temporary playground for the new DOM renderer. It is intended to be upstreamed here and replace the obsolete PolymerDomAdapter trick in this library.

After it is upstreamed, let us kill another repo and rename this to `angular-polymer`.

**Comment by BorntraegerMarc** [comment]
All clear. Maybe we want to do the renaming already now? As I think the upstreaming will not happen very soon.

And this way we do not confuse all people that are already using the library later on (which I will suspect will be more then at the moment).

Renaming/rebranding stuff is always kinda a hazzle. In my experience it's best to do it as soon as possible...

**Comment by platosha** [comment]
@BorntraegerMarc Right, makes sense. Done.

**Comment by BorntraegerMarc** [comment]
gracias :)
