### ISSUE TITLE
Polymer Dialog

### ISSUE THREAD

**Issue by lumisoftusa** [platosha/angular-polymer#126]
I am loving Polymer with Angular 2 all were fine and perfect but iam facing some serious problems in iPHONE and iPad .
1) If i use Polymer Dialog as a modal so i cannot even interact with the dialog its stuck.
2) Secondly my dialog even if i do not use modal dialog does not show on top of the screen.

Please help me my app is ready to publish but due to these two issues iam not able to move forward.

Thanks

Atif

**Comment by BorntraegerMarc** [comment]
Hello @lumisoftusa 
I've experienced similar issues as well. Please note that there are some bugs going on with paper-dialog itself from polymers side. Could you create a plunkr or something with some code?

My first mistake was that I had to put the dialog element in app.component.html to get it to work. Does this help you out?

**Comment by lumisoftusa** [comment]
Well I really need to fix this issue I was in pain a lot of pressure from the management because it was my decision to port Angular 2 apps into Polymer , Please community help me out this issue any trick or tweak .

**Comment by BorntraegerMarc** [comment]
Yes I would like to help you out but it is kinda difficult without your source code. Could you maybe create a plunkr or something?

Dialog generally works for me...

**Comment by lumisoftusa** [comment]
Well guys finally I have found the issue and the issue is If we use dialog inside panel-header so it miss behave in iOS so what I did is to replace panel header with simple HTML based panel and navigation bar and everything is in good shape.
