### ISSUE TITLE
Configure CI build

### ISSUE THREAD

**Issue by BorntraegerMarc** [platosha/angular-polymer#129]
Either use CircleCI or travis. My favorite is CircleCI for numerous of reasons. But maybe we vote. I can set it up as soon as I have some results...

Vote below:

**Comment by BorntraegerMarc** [comment]
CircleCI (https://circleci.com/)

**Comment by BorntraegerMarc** [comment]
Travis (https://travis-ci.org/)

**Comment by BorntraegerMarc** [comment]
@platosha Could you set this up? I don't have the necessary rights... And if you could create a free open source account at browserstack.com that would be cool :)

Then I could include some E2E tests...

**Comment by platosha** [comment]
CircleCI is enabled, builds are failing because of dependency and test setup issues. I don’t have time to look deeper right now.

**Comment by BorntraegerMarc** [comment]
Thanks. Will take a look.

**Comment by BorntraegerMarc** [comment]
Sorry, I forgot @platosha: Could you enable SSH for the CI? So we could debug when something goes wrong... I don't have permissions

**Comment by BorntraegerMarc** [comment]
And the tests don't run at the moment. Self assigned it to check again, once I have more time

**Comment by platosha** [comment]
Got it working in `feature/renderer` by adding karma and making some setup changes.
