### ISSUE TITLE
Using with angular-cli

### ISSUE THREAD

**Issue by jsertx** [platosha/angular-polymer#130]
I followed the documentation for using angular-polymer with angular-cli, but I cannot get it working.

I do everything, step by step, and I finally get:

`ERROR in {app_root_dir}/src/app/app.module.ts (7,32): Cannot find module '@vaadin/angular2-polymer'.)
`

Also, I find something interesting, in the folder node_modules/@vaadin/angular2-polymer there is no polymer-element file, only another node_modules folder with another folder caled rxjs inside.
<img width="816" alt="captura de pantalla 2017-02-10 a las 18 43 39" src="https://cloud.githubusercontent.com/assets/2692926/22837445/e00c3c52-efc0-11e6-9f54-60e0d8eaba98.png">

**Comment by BorntraegerMarc** [comment]
Yeah, there are quite some files missing from the dependency. I would recommend to clear the npm cache and try again

**Comment by jsertx** [comment]
@BorntraegerMarc I tried the following:
1) Uninstall the package:
`npm uninstall @vaadin/angular2-polymer`
2) Clear the cache of NPM
`npm cache clear`
3) Install forcing to download again the resource
`npm install --force @vaadin/angular2-polymer`

And still I have the same result, the funny fact is that it worked a few days ago in other project, but it was not an angular-cli one.

**Comment by BorntraegerMarc** [comment]
There was an deprecated way to install angular cli in the docs. changed it now to `npm install -g @angular/cli` does that help you?

**Comment by jsertx** [comment]
Yes @BorntraegerMarc , I did this way, I think I'll have to drop from angular-cli

**Comment by jsertx** [comment]
@BorntraegerMarc, It's curious, because I did this way, but now it worked.
Many thanks!
