### ISSUE TITLE
Angular-Polymer meetup 2/17/2017

### ISSUE THREAD

**Issue by MarkPieszak** [platosha/angular-polymer#136]
# 2/17/2017

#### Attended:
Alex, Anton, Wassim, Mark, Michael, Jai

# Topics:

- Currently held back at Polymer 1.(?) & Angular 2.2
  - Polymer 2 still only in preview (apis could drastically changed)
- Angular-Polymer-Renderer (was just a test repo) works with latest Angular (2.4.7)
  - Will be *merged* into 1 repo: Angular-Polymer

- **PolymerElement** might be removed temporarily until we can get it working
- PolymerElement currently doesn't work with AoT
- Anton walked through PolymerElement function
  - ~4 Directives (validation/form/change-detection)
  - Need to figure out a way to re-create these without being a Function (returning Directives)
    - We can't generate them at run-time, must be generated ahead of time. Must be static for AoT
    - Might need a tool to build-out all of them
    - JSON file where you register PolymerElements and then we generate them from there?
    - PolymerTeam uses some kind of tool to generate documentation?

- **Universal/Web-worker** compatibility
  - Have the library be ignored when rendering in those environments
  - `const Polymer: any = (<any>window).Polymer; // <-- will break Universal/web-workers`

- **(?)** Current/older implementation breaks Augury (due to ng.probe), does the new PolymerRenderer fix this?

# Summary:

- [`PolymerRenderer`](https://github.com/platosha/angular-polymer-renderer) merging to this repo here `angular-polymer`
  - PolymerRenderer itself is AoT compatible, if you don't use PolymerElement you'll be AoT compatible.
- Build-tool potentially needed to generate PolymerElement
- Try to get Rob Dodson to give insight on how we can proceed.
- Draft up a Design Doc.

**Comment by MarkPieszak** [comment]
Moved to Wiki here: https://github.com/platosha/angular-polymer/wiki/Angular-Polymer-Meetup-2-17-2017

**Comment by tallaxes** [comment]
The right name for what I referred to as ng-helper is `ng.probe`. It is helpful for debugging (e.g. see [here](https://juristr.com/blog/2016/02/debugging-angular2-console/)), but is also used by some other tooling, like Augury. Something about the way it was registering/wrapping the root renderer with debug version  ([around here](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/debug/ng_probe.ts#L64)) is (or maybe was) incompatible with angular-polymer.

**Comment by MarkPieszak** [comment]
Updated! Thanks @tallaxes
