### ISSUE TITLE
Error: Cannot find a differ supporting object [vaadin-combo-box]

### ISSUE THREAD

**Issue by mmenik** [platosha/angular-polymer#140]
I created a small project to test the integration of Polymer in Angular2. When I select an item from the combo box gives me the errror "Can not find something to differ supporting object" but I can not understand what the reason.
Attach the test project

[angular2-polymer.zip](https://github.com/platosha/angular-polymer/files/860823/angular2-polymer.zip)

**Comment by BorntraegerMarc** [comment]
@mmenik your project does not include a `bower.json`. I couldn't test it

**Comment by mmenik** [comment]
Sorry for my mistake, i have attach the bower.json
[angular2-polymer.zip](https://github.com/platosha/angular-polymer/files/861212/angular2-polymer.zip)

**Comment by BorntraegerMarc** [comment]
Hmm, seems like a problem with angular for me. Based on this: https://github.com/angular/angular/issues/6392

Does this help?

**Comment by BorntraegerMarc** [comment]
Closing until @mmenik is providing more feedback...
