### ISSUE TITLE
Renderer folder is not copied when adding it as npm dependency

### ISSUE THREAD

**Issue by BorntraegerMarc** [platosha/angular-polymer#144]
Had the problem again, that if I installed the package with "@vaadin/angular2-polymer": "file:../angular-polymer", that the whole "renderer" folder was missing in the target project. Had to copy it over manually. Maybe a import is missing?

**Comment by platosha** [comment]
@BorntraegerMarc I've updated the package.json and .npmignore configs, should fix this. Please try installing with `feature/renderer` branch.
