### ISSUE TITLE
vaadin date picker throwing Unhandled Promise rejection: TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by kjdevocht** [platosha/angular-polymer#19]
When I try and use the vaadin-date-picker as a directive in a component decorator, I get the following error. "Unhandled Promise rejection: TypeError: Cannot read property 'indexOf' of undefined" my component.ts file looks like this
`import { Component } from '@angular/core';
import { PolymerElement } from '@vaadin/angular2-polymer';

@Component({
  moduleId: module.id,
  selector: 'polymer-test-app',
  templateUrl: 'polymer-test.component.html',
  styleUrls: ['polymer-test.component.css'],
  directives: [
    PolymerElement('vaadin-combo-box'),
    PolymerElement('paper-input'),
    PolymerElement('vaadin-date-picker')
  ]
})
export class PolymerTestAppComponent {
  title = 'polymer-test works!';
  myLabel='Select a number'
  myValue = '4';
  myItems = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
  myDate = "1984-04-28";
}`

the combo-box works just fine so I am pretty sure I have the rest of my project set up correctly.

**Comment by TCMiranda** [comment]
Same problem here.
Appeared with `PolymerElement('vaadin-upload'),` at first.

This is the line reported:

``` Javascript
function PolymerElement(name) {
    var propertiesWithNotify = [];
    var arrayAndObjectProperties = [];
    var proto = Object.getPrototypeOf(document.createElement(name));
    var isFormElement = Polymer && Polymer.IronFormElementBehavior && proto.behaviors.indexOf(Polymer.IronFormElementBehavior) > -1;
                                                                                      ^^^
```

I am using webpack with ts loader.

Thanks!

**Comment by TCMiranda** [comment]
Ok... The problem occurs when the `PolymerElement` is called with a normal element. Not a polymer one.

So my solution was fix an html import for vaadin-upload.

The error should be more friendly though.
This is closed. Thanks!

**Comment by platosha** [comment]
This error appears if the element `'element-name'` has not been imported at the moment when `PolymerElement('element-name')` is called. Most probably caused by incorrect or missing HTML imports.

The error message was improved by PR #31.
