### ISSUE TITLE
Angular CLI doc wrong in the  docs site because double curly brackets

### ISSUE THREAD

**Issue by manolo** [platosha/angular-polymer#20]

**Comment by platosha** [comment]
This should be fixed in the docs website.  Solution: update 'jekyll-asciidoc' gem plugin to the master version. See vaadin/vaadin-docs#46

**Comment by platosha** [comment]
The issue was fixed in the docs website.

As a side effect of the fix, we can now remove the tutorial include workaround. This improvement is done in the PR #35.
