### ISSUE TITLE
Add Support for Angular-CLI

### ISSUE THREAD

**Issue by manolo** [platosha/angular-polymer#21]
- If the user installs the directive using `ng install angular2-polymer` everything in the project should be set to use the elements.
- Additionally we could add some kind of support for scaffolding.
- Everything should be set for vulcanizing when running `ng build`

**Comment by Splaktar** [comment]
angular-cli is in the process of moving to support webpack. It's currently in master, but not released yet. This work to support angular-cli will probably want to wait for the new webpack support to be released.

**Comment by manolo** [comment]
Thank Michael for the update. We will follow the status of webpack. We still have this task in our backlog and not started yet.
