### ISSUE TITLE
Vaadin components fail with Brocoli

### ISSUE THREAD

**Issue by pedrocortizo** [platosha/angular-polymer#22]
When I install vaadin-elements like vaadin-grid the build returns an error

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  A:/SERVIDOR/htdocs/angular2/weqom-polymer/tmp/broccoli_type_script_compiler-input_base_path-dW9fL9Rd.tmp/0/public/bower_components/vaadin-grid/demo/angular-grid-dom.ts (1, 49): Cannot find module 'angular2/angular2'.
...
...
```

Any solution to exclude the demo files of vaadin components, in order to use vaadin components propertly

Great job, greetings from Spain

**Comment by Saulis** [comment]
Hi!

Please use `1.1.x` version of `<vaadin-grid>` for Angular 2, preferably latest which is `1.1.0-beta4`

**Comment by pedrocortizo** [comment]
Works perfect. Thanks for the quick response @Saulis
