### ISSUE TITLE
karma error with directive angular2-polymer

### ISSUE THREAD

**Issue by sixrandanes** [platosha/angular-polymer#23]
Hello, 

I am facing an issue when I run my unit tests with karma on my project (angular-cli) with your directive.

15 06 2016 22:07:42.655:INFO [Chrome 51.0.2704 (Linux 0.0.0)]: Connected on socket /#nUTDqFlz7Z3B1E5WAAAA with id 90236010
Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function
at /home/dev/angular2-polymer-integration/node_modules/karma/lib/reporter.js:45:23

Karma crashes and never runs my tests.

I have followed your guide about how to configure a project with angular-cli (https://vaadin.com/vaadin-documentation-portlet/elements/angular2-polymer/ng-cli.html) but seems like I still miss something.

I tried to configure my karma.conf.js in many different ways but still got the same error.
Without importing and using your directive, my tests can be launched without any problems.

Finally, I followed the discussion about the issue #7 and can reproduce the same behavior by downloading the project from @harshabonthu :

https://github.com/harshabonthu/angular2-polymer-integration

Do you have any idea about this issue ?

---

Here is my environment :
node@6.2.1
npm@3.9.3
angular-cli@1.0.0-beta.6
karma@0.13.22
Chrome 51
Linux

**Comment by Saulis** [comment]
Hi!

Looks like the documentation is incomplete. It lacks things like appending imports for the polymer elements (mentioned by @manolo here: https://github.com/manolo/ng2-cli-polymer-app/commit/e26b4b62728f9d6972ce20c8a1b9ff4a7518ba7c), but also it looks like the tests start running before the elements get upgraded. 

I need to look more deeper into this.

**Comment by sixrandanes** [comment]
Hi,

Here is my karma.conf.js :

```
files: [
  { pattern: 'dist/vendor/es6-shim/es6-shim.js', included: true, watched: false },
  { pattern: 'dist/vendor/zone.js/dist/zone.js', included: true, watched: false },
  { pattern: 'dist/vendor/reflect-metadata/Reflect.js', included: true, watched: false },
  { pattern: 'dist/vendor/systemjs/dist/system-polyfills.js', included: true, watched: false },
  { pattern: 'dist/vendor/systemjs/dist/system.src.js', included: true, watched: false },

  { pattern: 'dist/vendor/rxjs/bundles/Rx.js', included: true, watched: false },

  { pattern: 'dist/vendor/zone.js/dist/async-test.js', included: true, watched: false },
  { pattern: 'config/karma-test-shim.js', included: true, watched: true },

  'dist/app/bower_components/webcomponentsjs/webcomponents.min.js',
  'dist/elements.html',

  // Distribution folder.
  { pattern: 'dist/**/*', included: false, watched: true }
],
```

I have already included the polyphills webcomponents.js and the elements.html which include all the import from polymer as well.

I was wondering if we shouldn't add  the file polymer-element.js  to do something like that : 

```
  { pattern: 'dist/vendor/@vaadin/angular2-polymer/src/polymer-element.js', included: true, watched: false},
```

I also tried with PhantomJS and got the same problem.

**Comment by sixrandanes** [comment]
It's weird...

I downloaded the projet from @manolo [manolo/ng2-cli-polymer-app](url) and seem like the process is not reproductible :

Sometimes the tests are running properly ... and sometimes facing the same issue....

Maybe there is something to do in the way the files are loaded.

**Comment by sixrandanes** [comment]
The console from the browser via karma gives me that error :

karma.js:87 Potentially unhandled rejection [4] TypeError: this.complete is not a function
    at Karma.error (http://localhost:9876/karma.js:133:10)

hope it helps.

**Comment by Saulis** [comment]
For Chrome, it seems that just making sure the custom elements are imported before anything else fixes the issue. But still not fast enough for polyfilled browsers.

``` js
files: [
      { pattern: 'dist/bower_components/webcomponentsjs/webcomponents-lite.js', included: true, watched: false },
      { pattern: 'dist/bower_components/vaadin-combo-box/vaadin-combo-box.html', included: true, watched: false },
      { pattern: 'dist/vendor/es6-shim/es6-shim.js', included: true, watched: false },
      { pattern: 'dist/vendor/zone.js/dist/zone.js', included: true, watched: false },
....
```

**Comment by sixrandanes** [comment]
Thanks @Saulis for your quick answer.

It works fine for me with Chrome when I remove the polyphills and import the custom elements first.
But still have the same problem with the ployfilled browsers (like Phantomjs@2.1.1).

Any idea about how to optimize the imports ?

Maybe, its not really anymore an issue related to Vaadin and has more to do with karma-phantomjs-launcher ?

**Comment by manolo** [comment]
The problem in non chrome browsers is that elements are imported asynchronously. 
Angular2-polymer cannot be instantiated asynchronously, so there is no easy way to run karma tests in non chrome browsers using karma configuration mechanism.

I did some research how to override the karma template `static/context.html` used in the test-iframe, but not found any solution to wrap the `window.__karma__.loaded()` in a callback.

probably using a custom script imported as `pattern: 'patch-karma.js'`, you could monkey patch the `window.__karma__.loaded()` to run after `Polymer` has been loaded

**Comment by Saulis** [comment]
Looks like the `karma-test-shim.js` that ships with the CLI alter clears the `window.__karma__.loaded()` and calls `window.__karma__start()` manually after system imports have been done. I was able to inject listener to wait for `WebComponentsReady` there and everything seems to be working nicely.

I'll try to come up with a nicely packaged solution for this.

**Comment by Saulis** [comment]
Couldn't find a feasible way to extend the current shim, so it might be easiest just to modify the vanilla shim. You can either wrap the whole import section inside an event listener that listens to `WebComponentsReady` or use promises like in the example below. Key thing here is that `WebComponentsReady` has to be fired before the Angular2 app module import begins.

``` js
/*global jasmine, __karma__, window*/
Error.stackTraceLimit = Infinity;
jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;

__karma__.loaded = function () {
};

var distPath = '/base/dist/';
var appPath = distPath + 'app/';

function isJsFile(path) {
  return path.slice(-3) == '.js';
}

function isSpecFile(path) {
  return path.slice(-8) == '.spec.js';
}

function isAppFile(path) {
  return isJsFile(path) && (path.substr(0, appPath.length) == appPath);
}

var allSpecFiles = Object.keys(window.__karma__.files)
  .filter(isSpecFile)
  .filter(isAppFile);

// Load our SystemJS configuration.
System.config({
  baseURL: distPath
});

var webcomponentsready = new Promise(function(resolve, reject) {
  document.addEventListener('WebComponentsReady', resolve);
});

webcomponentsready.then(function() {
  return System.import('system-config.js');
}).then(function() {
  // Load and configure the TestComponentBuilder.
  return Promise.all([
    System.import('@angular/core/testing'),
    System.import('@angular/platform-browser-dynamic/testing')
  ]).then(function (providers) {
    var testing = providers[0];
    var testingBrowser = providers[1];

    testing.setBaseTestProviders(testingBrowser.TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
      testingBrowser.TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS);
  });
}).then(function() {
  // Finally, load all spec files.
  // This will run the tests directly.
  return Promise.all(
    allSpecFiles.map(function (moduleName) {
      return System.import(moduleName);
    }));
}).then(__karma__.start, __karma__.error);
```

**Comment by Saulis** [comment]
Sent a PR to https://github.com/angular/angular-cli/pull/1154, if that gets approved, we can ship `angular2-polymer` with a script file that overrides `karma.loaded` to wait for `WebComponentsReady`

**Comment by components-stalker** [comment]
Moved away from review, since it depends on another ticket that won't be done any time now. Waiting for ng-cli to progress further.

**Comment by tehapo** [comment]
Angular CLI is moving to a Webpack setup. Closing this one now.
