### ISSUE TITLE
Production Mode + Vulcanize

### ISSUE THREAD

**Issue by evertonrobertoauler** [platosha/angular-polymer#33]
Hey there, 

I forked the https://github.com/vaadin-marcus/angular2-polymer-tutorial repository, and did some optimizations using gulp tasks: 

https://github.com/evertonrobertoauler/angular2-polymer-tutorial

https://github.com/vaadin-marcus/angular2-polymer-tutorial/issues/2

I'm interested in help to improve this idea, I didn't found a way to build a plugin for the angular-cli yet, but as son i find out, I'll try to do it.

Have a look, if you guys like it or have some better ideas I'd like to hear it.

**Comment by platosha** [comment]
Hi! Thanks for investigating this.

I’ve noticed that you added `bower_components/vaadin-grid/vaadin-grid.min.js` to polyfills list in the `angular-cli-build.js` file. It might be not acceptable that for every element with external scripts they should be included manually. Could it be avoided?

**Comment by Splaktar** [comment]
I was finally able to get Vulcanize to work for my project. You can see the code here: https://github.com/gdg-x/nexus/tree/angularFinalUpgrade. One of the key issues that I had to deal with was the location of my style element that enabled `iron-flex` layout features. Once I had that in the right location though, everything worked fine.

I'm using an NPM task to run Vulcanize.

**Comment by BorntraegerMarc** [comment]
Can we close this issue?
