### ISSUE TITLE
Support for Angular2 RC4?

### ISSUE THREAD

**Issue by gaithoben** [platosha/angular-polymer#40]
When do we expect support for RC4, i upgraded angular2 but i end up getting a blank screen.

**Comment by platosha** [comment]
Hi! By merging the PR #44 yesterday we fixed an issue that might have caused this problem. Could you, please, try if it works now with the latest version v1.0.0-beta2 of `@vaadin/angular2-polymer`?

**Comment by gaithoben** [comment]
Thank you, I will try once more and leave a comment later.

**Comment by gaithoben** [comment]
@platosha It works well. Thank you.

**Comment by platosha** [comment]
Great, thanks for informing us that it works for you.
