### ISSUE TITLE
Upgrade to the new Angular 2 forms module

### ISSUE THREAD

**Issue by platosha** [platosha/angular-polymer#43]
The forms module in Angular 2 had a breaking change, so now the new one is coming and the old one is going to be deprecated.

When running tests with Angular 2 rc4, I’ve got this warning in console:

```
ng_form_model.ts:48:


      *It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

```

We should probably upgrade to the new forms module.

**Comment by cschroeter** [comment]
It is great pity the project is abandoned
