### ISSUE TITLE
Getting warning when using angular-cli@webpack

### ISSUE THREAD

**Issue by 5amfung** [platosha/angular-polymer#54]
Project created using angular-cli@webpack would return the following warning when running `ng serve`.

```
WARNING in ./~/@vaadin/angular2-polymer/index.js
Cannot find source file 'index.ts': Error: Can't resolve './index.ts' in '/Users/foo/src/learn-vocab/node_modules/@vaadin/angular2-polymer'
 @ ./src/app/app.component.ts 11:0-58
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

WARNING in ./~/@vaadin/angular2-polymer/src/polymer-element.js
Cannot find source file 'polymer-element.ts': Error: Can't resolve './polymer-element.ts' in '/Users/foo/src/learn-vocab/node_modules/@vaadin/angular2-polymer/src'
 @ ./~/@vaadin/angular2-polymer/index.js 2:24-56
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

**Comment by tehapo** [comment]
Confirmed, I can also see the same warnings. The functionality is not affected though.

The reason for these warnings is that the distributed package does not include the TypeScript source files.

**Comment by Chabane** [comment]
I have the same warning. A fix is envisaged?

**Comment by Chabane** [comment]
It doesn't work with Firefox and IE11, I have this error : 
TypeError: Polymer is undefined

`<anonyme>
 main.bundle.js:74673
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:14863
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:64712
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:64699
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:64875
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:64140
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:64195
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:49483
__webpack_require__()
 inline.js:53
<anonyme>
 main.bundle.js:79944
__webpack_require__()
 inline.js:53
webpackJsonpCallback()
 inline.js:24
<anonyme>`

**Comment by aegyed91** [comment]
Hmm i have no such warnings. I dont know how `angular-cli` works, but you can mix and match the code [in this project](https://github.com/codewareio/angular2-ts-seed/tree/polymer). It uses webpack and rc5. Make sure you investigate the polymer branch.

**Comment by platosha** [comment]
Possibly fixed in https://github.com/angular/angular-cli/commit/22a6b59dd429356bd617ae3dfceb51335aa815d2

**Comment by JohannesRudolph** [comment]
I'm seeing similar errors when importing an npm library in tests via `ng test`, not sure if this is related.

**Comment by BorntraegerMarc** [comment]
I don't see the warnings anymore when building with webpack... If it pops up again -> Feel free to re open
