### ISSUE TITLE
Unable to integrate with angular2-seed

### ISSUE THREAD

**Issue by ghost** [platosha/angular-polymer#56]
I have been trying to integrate angular2-polymer with angular2-seed from past 2 days; but couldn't make it.

Need help very badly!

Here is the error in console:
![vaadin_error](https://cloud.githubusercontent.com/assets/6713590/17553507/c5968e1e-5f23-11e6-9d33-42d28fb3e9cf.JPG)

**Comment by aegyed91** [comment]
@surya84 check out [angular2-ts-seed](https://github.com/codewareio/angular2-ts-seed/tree/polymer)'s polymer branch. It runs on rc5 and works fine.

**Comment by Saulis** [comment]
@surya84 did you try the suggestion above? Is this still an issue?

**Comment by BorntraegerMarc** [comment]
Closing the issue as there is no more feedback ...
