### ISSUE TITLE
Firefox/IE11 - Angular-cli/Webpack - TypeError: Polymer is undefined

### ISSUE THREAD

**Issue by Chabane** [platosha/angular-polymer#57]
Hi,

Project created using angular-cli@webpack would return the following errors when running ng serve, in Firefox and IE11. 

Polymer is loaded after main.ts.

> TypeError: Polymer is undefined
> 
> <anonyme> main.bundle.js:74673 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:14863 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:64712 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:64699 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:64875 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:64140 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:64195 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:49483 **webpack_require**() inline.js:53 <anonyme> main.bundle.js:79944 **webpack_require**() inline.js:53 webpackJsonpCallback() inline.js:24 <anonyme>

How can I do without using document.addEventListener('WebComponentsReady', function() [..] in index.html?

I put something like that into index.html : 

`<script>
      window.Polymer = window.Polymer || {};
      window.Polymer.dom = 'shadow';
    </script>`

But I got this error :
TypeError: Polymer.Settings is undefined

**Comment by platosha** [comment]
Hi,

The cause of the error you have is that the Polymer library has not been loaded and initialized yet at the time when the `angular2-polymer` directives are trying to access it. It’s not possible workaround this by just declaring the `window.Polymer` object.

The Polymer library and elements are imported with HTML Imports. Chrome has a native support of them, they are loaded synchronously in it, there are no errors. But in the other browsers, the HTML Imports are working through a polyfill, so they are async, therefore the Polymer gets loaded later, after the synchronous `<script src="">` imports.

You have to postpone the angular application bootstrap after the `WebComponentsReady` event is dispatched. There is no other way around it we know.

Unfortunately, we don’t have the exact instructions on how to do it for the `angular-cli@webpack` projects. But we do have plans on improving the cli support. Closing this issue as a part of the #21.

**Comment by Chabane** [comment]
@platosha 

Thanks, I will wait.

**Comment by nikoTM** [comment]
Hello @platosha,

Is it possible to bundle up the HTML import and load locally as a workaround for this, until an official release ? If so, please share how to bundle it. Thanks.

**Comment by platosha** [comment]
@nikoTM you can use the [vulcanize](https://github.com/Polymer/vulcanize) tool for that. For example:

```
$ npm install -g vulcanize
$ vulcanize --inline-scripts src/index.html > src/index.bundle.html
```

**Comment by nuwan-sl** [comment]
Thanks platosha. it is working

**Comment by Chabane** [comment]
Thank's,
@platosha I tried to do something like that in main.ts, but it doesn't work  : 

```
document.addEventListener('WebComponentsReady', function() {
   platformBrowserDynamic().bootstrapModule(AppModule);
});
```

@nuwanwickrmanayaka can u expose your solution please?

**Comment by platosha** [comment]
@Chabane perhaps I was a bit wrong about the bootstrap. Please try to postpone both import and bootstrap. See this guide: https://github.com/vaadin/angular2-polymer/blob/master/docs/ng-cli-webpack.adoc

**Comment by Chabane** [comment]
Thank you @platosha that's work fine!

**Comment by niveo** [comment]
@platosha 
@Chabane 

 https://github.com/vaadin/angular2-polymer/blob/master/docs/ng-cli-webpack.adoc

can't find webcom... in  index.html

<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
