### ISSUE TITLE
Cannot import app-grid

### ISSUE THREAD

**Issue by aegyed91** [platosha/angular-polymer#58]
Cannot import [app-grid](https://elements.polymer-project.org/elements/app-layout?active=app-grid). 

``` ts
const PolymerComponents = [
  PolymerElement('app-drawer'),
  PolymerElement('app-drawer-layout'),
  // PolymerElement('app-grid'),
  PolymerElement('app-scrollpos-control'),
  PolymerElement('app-header'),
  PolymerElement('app-toolbar'),
  PolymerElement('app-header-layout'),
  PolymerElement('app-box')
];
```

It is probably because the `app-grid` folder doesn't contain an `app-grid.html` but an `app-grid-style.html`. And `PolymerElement`'s name input, i keep getting [this error](https://github.com/vaadin/angular2-polymer/blob/master/src/polymer-element.ts#L75-L77).

``` html
<!-- bower_components/app-layout/app-layout.html -->
<link rel="import" href="helpers/helpers.html">
<link rel="import" href="app-drawer/app-drawer.html">
<link rel="import" href="app-drawer-layout/app-drawer-layout.html">
<link rel="import" href="app-grid/app-grid-style.html">
<link rel="import" href="app-header/app-header.html">
<link rel="import" href="app-header-layout/app-header-layout.html">
<link rel="import" href="app-scrollpos-control/app-scrollpos-control.html">
<link rel="import" href="app-toolbar/app-toolbar.html">
<link rel="import" href="app-box/app-box.html">
```

ping @platosha

**Comment by platosha** [comment]
Not an issue. `app-grid` is a pseudo-element. It does not register itself under a custom HTML element name. In the `app-grid-style.html` file, there are no elements defined, but only a style module.

As long as you don’t have `<app-grid>`, there is no need to do anything special about `app-grid` for the `PolymerElement` directives as well. You can safely skip declaring it in the directives, like you did already.

The same applies to `iron-flex-layout` and all the other pseudo-elements.
