### ISSUE TITLE
Cant bind property primitive types

### ISSUE THREAD

**Issue by aegyed91** [platosha/angular-polymer#60]
I can only bind the [`swipeOpen`](https://elements.polymer-project.org/elements/app-layout?active=app-drawer#property-swipeOpen) property primitive type of `app-drawer` with `<app-drawer [swipeOpen]="true"></app-drawer>`. This doesn't work: `<app-drawer swipeOpen></app-drawer>`.

But i don't quite understand because the [opened](https://elements.polymer-project.org/elements/app-layout?active=app-drawer#property-opened) property works fine`<app-drawer opened></app-drawer>`

cc @platosha

**Comment by platosha** [comment]
Please try: `<app-drawer swipe-open></app-drawer>`. The property names are in camelCase, while the attribute names are in kebab-case.

**Comment by aegyed91** [comment]
ahh cool, it works
