### ISSUE TITLE
Is the directive compatible angular2@rc5 ?

### ISSUE THREAD

**Issue by sixrandanes** [platosha/angular-polymer#61]
Hello,

I tried to upgrade my project with the last release of angular (rc5).

When I am using modules in angular2@rc5 way, the angular2-polymer directive seems not to be taking into account as a directive.

I"ve got this error :

> Can't bind to 'invalid' since it isn't a known property of 'paper-input'.
> 1. If 'paper-input' is an Angular component and it has 'invalid' input, then verify that it is part of this module.
> 2. If 'paper-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
>  ("    <paper-input  id="code" formControlName="code" label="code" ngDefaultControl
>                    [ERROR ->][invalid]="true"
>                    [errorMessage]="error"
>                    required maxlength="3" "): PolyAppComponent@15:19

 I have reproduced the problem in two small projects :

https://github.com/sixrandanes/angular2-polymer-integration-rc4 (everything is ok)
https://github.com/sixrandanes/angular2-polymer-integration-rc5 (error template parser)

Thanks,

**Comment by unnamed666** [comment]
got similiar error but after adding CUSTOM_ELEMENTS_SCHEMA to ngModule schemas array its working fine - you got insruction how to fix in your error message :)

**Comment by sixrandanes** [comment]
Thanks a lot for your answer !!

I close this issue as it works well with adding CUSTOM_ELEMENTS_SCHEMA to NgModule.schema.
I missed the point when I red the error message.

Awesome !

**Comment by hrandika** [comment]
@sixrandanes can you please elaborate more on this? (May be a small sample project). I'm trying my self with RC5.

**Comment by sixrandanes** [comment]
Here is the detail :

@NgModule({
  imports:      [ ... ],
  declarations: [
...
  ],
  providers:    [ ... ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export default class XXXModule { }

**Comment by ootwch** [comment]
I tried the below module, which I would import into the modules using polymer elements (almost all of them..), but this does not seem to work either (`Can't bind to 'icon' since it isn't a known property of 'iron-icon'`).

``` typescript
// polymer-wrapper.module.ts


import {CommonModule} from '@angular/common';
import {NgModule, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';

import { PolymerElement } from '@vaadin/angular2-polymer';


const POLYMER_MODULES = [
'paper-button',
'paper-dropdown-menu',
'paper-submenu',
'paper-item',
'paper-header-panel',
'paper-toolbar'
];

let polymerDeclarations = POLYMER_MODULES.map(PolymerElement);


@NgModule({
  imports: [CommonModule],
  declarations: polymerDeclarations,
  exports: polymerDeclarations,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class PolymerModule {}

```
