### ISSUE TITLE
Still relevant?

### ISSUE THREAD

**Issue by bertvh** [platosha/angular-polymer#63]
Just did a test setup using angular rc.4 and an few Polymer elements. I didn't have to do anything. Attribute bindings seemed to work properly, events also worked smoothly.

What am I missing? Or, what should I try that won't work without the angular2-polymer component?

**Comment by platosha** [comment]
Try the following:
- Two-way bindings, should update `componentProperty`: `<paper-input [(value)]="componentProperty"></paper-input><p>The value is: {{componentProperty}}</p>`
- Deep property changes. Render `<iron-list>` with items bound to an array, then modify an array item from the component and from the Polymer element. The changes should propagate in both ways.
- Polymer’s Shady DOM compatibility for component templates. The Polymer elements that accept DOM contents (app-layout, paper-dropdown-menu, etc..) should work correctly and update if the contents are changed dynamically. Try to use the `<app-layout>` elements in Angular component templates.
- Use Polymer elements inside Angular forms (the deprecated forms should work, support for the new forms module is coming in #55)
- Style Polymer elements with custom CSS properties and mixins defined in Angular component styles

**Comment by bertvh** [comment]
Cool. Will try!

VERY nice that you support the forms API. I already gave up on that, but this means I shouldn't.

Thanks for the great plugin.
