### ISSUE TITLE
Update to rc5

### ISSUE THREAD

**Issue by components-stalker** [platosha/angular-polymer#67]

**Comment by Chabane** [comment]
Thanks. Is it possible to publish the beta3 in npm?
npm install --save @vaadin/angular2-polymer@1.0.0-beta3 returns a 404 error.

**Comment by tehapo** [comment]
@Chabane Oh sorry, I forgot to run `npm publish` after tagging the release. 😄  Fixed.

**Comment by Chabane** [comment]
Thanks :+1:
