### ISSUE TITLE
Google map attribute binding

### ISSUE THREAD

**Issue by maxmumford** [platosha/angular-polymer#71]
Hi,

I'm trying to bind the google-map and google-map-marker latitude and longitude attributes to component properties like so:

```
<google-map-marker [latitude]="position?.coords.latitude" [longitude]="position?.coords.longitude" title="You be here!"></google-map-marker>
```

... but get the following error:

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'latitude' since it isn't a known property of 'google-map'.
1. If 'google-map' is an Angular component and it has 'latitude' input, then verify that it is part of this module.
2. If 'google-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
<paper-input label="Input label"></paper-input>
<div [hidden]="!position">
  <google-map [ERROR ->][latitude]="position?.coords.latitude" [longitude]="position?.coords.longitude" fit-to-markers>
    "): AppComponent@36:14
Can't bind to 'longitude' since it isn't a known property of 'google-map'.
1. If 'google-map' is an Angular component and it has 'longitude' input, then verify that it is part of this module.
2. If 'google-map' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("l"></paper-input>
<div [hidden]="!position">
  <google-map [latitude]="position?.coords.latitude" [ERROR ->][longitude]="position?.coords.longitude" fit-to-markers>
    <google-map-marker latitude="position?."): AppComponent@36:53 ; Zone: <root> ; Task: Promise.then ; Value: 
```

Is what I'm trying to do supported? How should it be done?

Thanks
Max

**Comment by platosha** [comment]
Hi! Angular v2.0.0-rc.5 introduced stricter checks on the component templates. Namely, binding to any properties unknown to Angular is not allowed by default anymore. As the error message says, since `google-map` is a Web Component, you should specify CUSTOM_ELEMENTS_SCHEMA in your @NgModule to allow unknown properties. Example:

``` typescript
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

// ...

@NgModule({
  // ...
  schemas:  [ CUSTOM_ELEMENTS_SCHEMA ]
})
export class AppModule { }
```

The documentation updates covering usage with Angular v2.0.0-rc.5 are coming in the PR #69.

**Comment by maxmumford** [comment]
Ah I see, I expected the module to be aware of all of the inputs for the components it provides. Whitelisting all attributes like that does feel a little bit hacky... Are there any plans to explicitly support this without the need of CUSTOM_ELEMENTS_SCHEMA?

Otherwise great module, very easy to set up :)

**Comment by Chabane** [comment]
@maxmumford If you are using angular-cli@webpack, you have to follow this documentation : 
https://github.com/vaadin/angular2-polymer/blob/master/docs/ng-cli-webpack.adoc

Thanks @platosha @tehapo.

**Comment by platosha** [comment]
@maxmumford Agree. This would be a nice improvement.

Angular’s codebase is still changing quickly. We are focused on keeping this package up-to-date and functioning for now. No certain plans on improvements yet, but we have ideas. This could be done as a part of #70, perhaps.

**Comment by maxmumford** [comment]
#70 looks interesting and imo is definitely a use case people will come across. In the meantime this module will work nicely, to be honest I'm just happy that something so comprehensive exists while NG2 is still so young... Thanks again for your help.

**Comment by kamlekar** [comment]
In my case, I was copying the code from another colleagues work. And I had missed adding the APIKEY related code. Once I added that code, things were were working fine :)
