### ISSUE TITLE
Cannot set property 'persistent' of undefined when trying to use app-layout 

### ISSUE THREAD

**Issue by maxmumford** [platosha/angular-polymer#74]
Hi all,

vaadin/angular2-polymer is working correctly for some elements like paper-input, but when it comes to implementing app-layout I'm getting errors:

![app-layout errors](http://i145.photobucket.com/albums/r205/maxmumford/Screen%20Shot%202016-08-25%20at%2016.03.34_zpsdvcyez5w.png)

The strange thing is that the errors are intermittent, appearing 95% of the time, the other 5% the app-layout works correctly without any errors. I can't find any pattern to this however, which leads me to think it's an issue with the load order or code execution order.

Here's my index.html (with script tags generated by webpack):

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset=UTF-8>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My App</title>
    <base href="/">

    <link rel="stylesheet" href="styles.css">

    <!-- polymer -->
    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="/bower_components/paper-styles/color.html">
    <link rel="import" href="/bower_components/paper-styles/default-theme.html">
    <link rel="import" href="/bower_components/paper-styles/typography.html">
    <link rel="import" href="/bower_components/paper-styles/shadow.html">

    <link rel="import" href="/bower_components/iron-icons/iron-icons.html">
    <link rel="import" href="/bower_components/app-layout/app-scroll-effects/app-scroll-effects.html">
    <link rel="import" href="/bower_components/app-layout/app-layout.html">


    <link rel="import" href="/bower_components/paper-icon-button/paper-icon-button.html">
    <link rel="import" href="/bower_components/paper-menu/paper-menu.html">
    <link rel="import" href="/bower_components/paper-item/paper-item.html">

    <link rel="import" href="/bower_components/paper-input/paper-input.html">
    <link rel="import" href="/bower_components/google-map/google-map.html">

  </head>
  <body>

    <my-app>
      Loading...
    </my-app>

  <script type="text/javascript" src="polyfills.bundle.js"></script><script type="text/javascript" src="vendor.bundle.js"></script><script type="text/javascript" src="main.bundle.js"></script></body>
</html>
```

my main.browser.ts (entry point that delays app bootstrapping until webcomponents is ready):

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';

document.addEventListener('WebComponentsReady', function() {

  platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.error(err));

});
```

my app.module.ts:

```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { routing, appRoutingProviders } from './app.routing';

// components
import { PolymerElement } from '@vaadin/angular2-polymer';
import { AppComponent }  from './app.component';

@NgModule({
  imports:      [ 
    BrowserModule,
    routing
  ],
  declarations: [ 
    AppComponent,

    // polymer
    PolymerElement('app-drawer-layout'),
    PolymerElement('app-drawer'),
    PolymerElement('app-header-layout'),
    PolymerElement('app-header'),
    PolymerElement('app-toolbar'),
    PolymerElement('paper-menu'),
    PolymerElement('paper-item'),
    PolymerElement('paper-input'),
    PolymerElement('google-map'),
    PolymerElement('paper-icon-button')
  ],
  providers:    [ 
    appRoutingProviders
  ],
  schemas:  [ CUSTOM_ELEMENTS_SCHEMA ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

my app.component.html:

```
<app-drawer-layout>
    <app-drawer>
        <paper-menu>
          <paper-item>Home</paper-item>
          <paper-item>About</paper-item>
          <paper-item>Schedule</paper-item>
          <paper-item>Account</paper-item>
        </paper-menu>
    </app-drawer>
    <app-header-layout>
        <app-header reveals effects="waterfall">
            <app-toolbar>
                <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
                <div title>{{ title }}</div>
                <paper-icon-button icon="search"></paper-icon-button>
            </app-toolbar>
        </app-header>
        <!-- Main content -->
        <div class="layout vertical" style="padding: 16px;">
            <router-outlet></router-outlet>
        </div>
    </app-header-layout>
</app-drawer-layout>
```

Any ideas why those errors are appearing?

Thanks
Max.

**Comment by platosha** [comment]
Hi! Looks like `<app-drawer-layout>` is trying to access `<app-drawer>`, while it has not been attached yet. This is how Angular templates work normally, the wrapper elements are attached before their children, so probably we can not fix this.

Could be a bug in `<app-drawer-layout>`. For example, `<app-header-layout>` has a similar structure, but works fine. I’ve noticed, that in `<app-header-layout>` there are multiple checks to avoid producing errors when it tries to access `<app-header>`, but no such checks are there in `<app-drawer-layout>`. We will try to find out.

**Comment by maxmumford** [comment]
Thanks @platosha, yeah fingers crossed it's an upstream issue and not a framework limitation. Thanks for your support

**Comment by 5amfung** [comment]
The loading order has something to do with the issue.
- When running on Chrome, if I don't wait for WebComponentsReady event and immediately bootstrap the angular app, everything works without any problem on Chrome, but not Safari.
- If I wait for WebComponentsReady before bootstrapping the app, it works on Safari, but not Chrome.  When it doesn't work on Chrome, that's where I get would get `Cannot read property 'getWdith' of undefined` from `polymer-mini.html` and `Cannot set property 'persistent' of undefined` error from `app-drawer-layout.html`.  As far as I know, we should wait for WebComponentsReady before bootstrapping the angular app.

**Comment by platosha** [comment]
It looks like this issue was resolved in the `<app-drawer-layout>`, see: https://github.com/PolymerElements/app-layout/pull/313

Please update the bower dependencies and try again. The current version of the  `<app-drawer-layout>` works for me.
