### ISSUE TITLE
vaadin-date-picker - formControlName not supported as expected

### ISSUE THREAD

**Issue by Chabane** [platosha/angular-polymer#75]
Hi,

Thanks for the beta3. I tried to use the new form version of Angular 2 but it doesn't work with vaadin-date-picker. I got this error :  

`More than one custom value accessor matches form control with unspecified name attribute`

```
<form [formGroup]="userForm">
          <vaadin-date-picker label="Birthday" formControlName="birthday"
            [(value)]= "birthdayStr">
          </vaadin-date-picker>`
</form>
export class UserComponent implements OnInit {
  userForm : FormGroup;
  birthdayStr : string;
   birthday : FormControl;
   constructor(private fb: FormBuilder) {
    this.birthday= fb.control('', Validators.required);
     this.userForm = fb.group(
      {
        birthday: this.birthday
      });
   }

```

Thanks!

**Comment by maxmumford** [comment]
I'm also having this issue with paper-input:

Trying to implement two way data binding with paper-input using the latest version (1.0.0-beta3) with the following code:

```
<paper-input label="Email" name="registerEmail" id="registerEmail" [(ngModel)]="userRegister.email"
          required></paper-input>
```

and I get the following error message:

`More than one custom value accessor matches form control with unspecified name attribute`

Removing the ngModel attribute stops the error from appearing and the paper-input element renders correctly but of course isn't bound to the userRegister member.

**Comment by tomivirkki** [comment]
Hi @Chabane 
Played around with your example snippet at https://embed.plnkr.co/4XBiyW/. Got `<vaadin-date-picker>` functioning ok as a FormControl there. Am I missing something?

**Comment by Chabane** [comment]
@tomivirkki

Thanks for the plnkr. I am using ReactiveFormsModule instead of FormsModule.

I copied the code on plnkr and I have another error :

> Error: No value accessor for form control with name:

I can fix this with ngDefaultControl, but I am not supposed to use it.

**Comment by Chabane** [comment]
That's work fine with beta5
