### ISSUE TITLE
More than one custom value accessor matches form control with unspecified name attribute

### ISSUE THREAD

**Issue by maxmumford** [platosha/angular-polymer#77]
Trying to implement two way data binding with paper-input using the latest version (1.0.0-beta3) with the following code:

```
<paper-input label="Email" name="registerEmail" id="registerEmail" [(ngModel)]="userRegister.email"
          required></paper-input>
```

and I get the following error message:

`More than one custom value accessor matches form control with unspecified name attribute`

Removing the ngModel attribute stops the error from appearing and the paper-input element renders correctly but of course isn't bound to the userRegister member. Any ideas how to fix this?

Thanks
Max

**Comment by Chabane** [comment]
It's the same issue as #75

**Comment by maxmumford** [comment]
Oops, didn't see that one. Let's consolidate into #75
