### ISSUE TITLE
Incompatible with Angular2 rc.6

### ISSUE THREAD

**Issue by DevWurm** [platosha/angular-polymer#78]
When using Angular2 Release Candidate 6, I'm not able to load my app, when including Polymer Components via `angular2-polymer`, because of the following error:

``` javascript
17:37:59.764 TypeError: core_1.provide is not a function
PolymerElement()main.bundle.js:71861
AppModule<()main.bundle.js:58569
<anonymous>main.bundle.js:58556
__webpack_require__()inline.js:53
<anonymous>main.bundle.js:58955
__webpack_require__()inline.js:53
<anonymous>main.bundle.js:34322
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask()polyfills.bundle.js:3277
Zone</Zone</Zone.prototype.runTask()polyfills.bundle.js:3177
ZoneTask/this.invoke()polyfills.bundle.js:3344
t/</<()localhost:4200:25
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask()polyfills.bundle.js:3277
Zone</Zone</Zone.prototype.runTask()polyfills.bundle.js:3177
ZoneTask/this.invoke()polyfills.bundle.js:3344
1main.bundle.js:71861:13
```

Probably because of [this](https://github.com/angular/angular/commit/bec5c5f#diff-8deabf0df78205f67c15546ad1410556L399) change in the Angular2 API.

This is the code, where the Error comes from:

``` javascript
import {NgModule, CUSTOM_ELEMENTS_SCHEMA}      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent }  from './app.component';
import { MainComponent } from "./main/main.component";
import {PolymerElement} from "@vaadin/angular2-polymer";
import {routing} from "./app.routing";
import {ConfigFileApiConfigurationService} from "./shared/configuration/config-file-api-configuration.service";
import {API_CONFIGURATION_TOKEN} from "./shared/configuration/api-configuration";
import {HttpModule} from "@angular/http";

@NgModule({
  imports: [
    BrowserModule,
    routing,
    HttpModule
  ],
  declarations: [
    AppComponent,
    MainComponent,
    PolymerElement('paper-scroll-header-panel')
  ],
  providers: [
    {provide: API_CONFIGURATION_TOKEN, useClass: ConfigFileApiConfigurationService}
  ],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```

**Comment by emilianosantucci** [comment]
Same issue with RC6

**Comment by niveo** [comment]
This work for me. I think ^.^

clone the project change and compile.

`
import {Provider...} from '@angular/core';

import { NgControl as OldNgControl, NG_VALUE_ACCESSOR as OLD_NG_VALUE_ACCESSOR,
  FormControlName, NG_VALUE_ACCESSOR } from '@angular/forms';

   providers: [{
          provide: OLD_NG_VALUE_ACCESSOR, 
          useExisting: forwardRef(() => formElementDirective),
          multi: true
      },{
          provide : NG_VALUE_ACCESSOR, 
          useExisting: forwardRef(() => formElementDirective),
          multi: true
      }
    ],
`

or change polymer-element.js

[https://www.dropbox.com/s/l8j2kpdo9holfdf/polymer-element.js?dl=0](url)

[https://www.dropbox.com/s/dp0oqer2w8jhycb/polymer-element.ts?dl=0](url)

**Comment by emilianosantucci** [comment]
Hi @niveo, we can't reach dropbox links :(, can use plunker instead?
I've tried a similar approach but something went wrong when extends `BrowserDomAdapter`, receiving errors on browser console below:

``` log
unexpected token export [...]
```

p.s.: which command launch to compile it?

**Comment by niveo** [comment]
clone https://github.com/vaadin/angular2-polymer.git

change package.json

```
"@angular/common": "^2.0.0-rc.6",
"@angular/core": "^2.0.0-rc.6",
"@angular/forms": "^2.0.0-rc.6",
"@angular/platform-browser": "^2.0.0-rc.6"

"@angular/compiler": "^2.0.0-rc.6",
"@angular/platform-browser-dynamic": "^2.0.0-rc.6"
```

NOW
**npm install**

REMOVE

import { NgControl as OldNgControl, NG_VALUE_ACCESSOR as OLD_NG_VALUE_ACCESSOR } from '@angular/common';

ADD

import { NgControl as OldNgControl, NG_VALUE_ACCESSOR as OLD_NG_VALUE_ACCESSOR, 
  FormControlName, NG_VALUE_ACCESSOR } from '@angular/forms';

CHANGE
providers: [{
provide: OLD_NG_VALUE_ACCESSOR, 
useExisting: forwardRef(() => formElementDirective),
multi: true
},{
provide : NG_VALUE_ACCESSOR, 
useExisting: forwardRef(() => formElementDirective),
multi: true
}
]

REMOVE FILE
polymer-element.spec.ts

npm run prepublish

REPLACE FILE FOR YOUR PROJECT "node_module/@vaadin/angular2-polymer/src/" 

polymer-element.js

COPY AND PAST IN YOUR BROWSER
https://www.dropbox.com/s/l8j2kpdo9holfdf/polymer-element.js?dl=0
https://www.dropbox.com/s/dp0oqer2w8jhycb/polymer-element.ts?dl=0

**Comment by emilianosantucci** [comment]
I did same steps but nothing changed :(.
Now I've branched my project and downgrade the master on RC5. Maybe the issue is also linked on my platform (Meteor) and its angular2-compilers package.

Anyway, thanks @niveo for all :D.

**Comment by platosha** [comment]
Hello! Thanks for filing this issue and sharing the information.

We’re working on the solution, see PR #80. The pull request is currently under a team review, but your feedback would be also helpful. Please try the [upgrade branch](https://github.com/vaadin/angular2-polymer/tree/upgrade/angular-v2.0.0-rc.6) and say if it works for you.

**Comment by niveo** [comment]
angular2-polymer-upgrade-angular-v2.0.0-rc.6

it's works, thanks.

**Comment by emilianosantucci** [comment]
@platosha it's works, thanks.

My issue was on using `[...] extends BrowserDomAdapter` instead `[...] extends __platform_browser_private__.BrowserDomAdapter` :D.

Have you plan an official release date?
