### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by platosha** [platosha/angular-polymer#8]
The first priority is to test if the tutorial can be followed end completed by developers. I.e., test for the functionality first.

The “feels at home” experience testing is the second priority.

**Comment by manolo** [comment]
Assigning @marlonrichert who is in charge of User testing right now.

Tutorial is live in github through this URL:

https://github.com/vaadin/angular2-polymer/blob/master/docs/tutorial.adoc

**Comment by jouni** [comment]
Angular 2 + Polymer usability test recording + observations now here: https://drive.google.com/drive/folders/0B2ikCcK6RPA0WkVubFFyQjlyR0U

**Comment by jouni** [comment]
New usability test recording and observations over here: https://drive.google.com/drive/folders/0B2ikCcK6RPA0WkVubFFyQjlyR0U
