### ISSUE TITLE
Two way binding with Angular 2 - Google Web Component ( chart ) is not working

### ISSUE THREAD

**Issue by ythanaseelan** [platosha/angular-polymer#85]
With below angular component and template, the graph comes up fine with initial data, but when the data is changed from angular component, the chart is not refreshed with new data.

On a related note, when used through, the document element ( commented code ), it works fine.

Angular component:( excerpt )

> public dataForColumnChart = [["Status", "P1", "P2"],
>                    ["Ready", 5000, 400],
>                    ["Allocated", 1170, 4560],
>                    ["Waiting", 6650, 1120]];
> updateData()
>     {
>         //var chart = document.getElementById('mutating-chart');  
>         window.setTimeout(function() {
>         /`*chart.data = [["Status", "P1", "P2"],
>                        ["Ready", Math.random() * 10000, Math.random() * 10000],
>                        ["Allocated", Math.random() * 10000, Math.random() * 10000],
>                        ["Waiting", Math.random() * 10000, Math.random() * 10000]];
>         this.dataForColumnChart=[];`*/
>         this.dataForColumnChart=[["Status", "P1", "P2"],
>            ["Ready", Math.random() \* 10000, Math.random() \* 10000],
>            ["Allocated", Math.random() \* 10000, Math.random() \* 10000],
>            ["Waiting", Math.random() \* 10000, Math.random() \* 10000]];
>         }, 3000);  
>     }

Template: ( excerpt )
`<google-chart id=mutating-chart (google-chart-ready)="updateData()"   
     type="column"
     [options]="columnChartOptions"
     [data]="dataForColumnChart">`
`</google-chart>`

**Comment by Saulis** [comment]
Looking at this snippet, looks like the function given to `setTimeout` isn't scoped properly – `this.dataForColumnChart` isn't the components property.

Does this work? 

``` js
window.setTimeout(function() {
  this.dataForColumnChart=[["Status", "P1", "P2"],
    ["Ready", Math.random() * 10000, Math.random() * 10000],
    ["Allocated", Math.random() * 10000, Math.random() * 10000],
    ["Waiting", Math.random() * 10000, Math.random() * 10000]];
}.bind(this), 3000);
```

**Comment by BorntraegerMarc** [comment]
Closing until feedback from @ythanaseelan is provided...
