### ISSUE TITLE
Error using PolymerElements with angular-cli-webpack

### ISSUE THREAD

**Issue by mscharp** [platosha/angular-polymer#87]
Following the steps in the angular-cli-webpack.adoc guide for using the PolymerElements results in an error: `Uncaught Unexpected value 'class0' declared by the module 'AppModule'`

It seems to stem from putting any of the PolymerElement() in the declarations tag of NgModule as such:

`@NgModule({
    ...
    declarations: [ AppComponent,
        PolymerElement('paper-input')
    ],
    ...
})` 

Any help would be greatly appreciated, thanks!

angular-cli-version: 1.0.0-beta.11-webpack.8
vaadin version: "@vaadin/angular2-polymer": "^1.0.0-beta4",
bower dependencies: 

`{
    "polymer": "^1.6.1",
    "app-layout": "^0.10.4",
    "iron-collapse": "^1.2.1",
    "iron-icons": "^1.1.3",
    "paper-card": "PolymerElements/paper-card#^1.1.2",
    "paper-checkbox": "PolymerElements/paper-checkbox#^1.4.0",
    "paper-dropdown-menu": "^1.4.0",
    "paper-fab": "^1.2.0",
    "paper-icon-button": "^1.1.2",
    "paper-input": "^1.1.19",
    "paper-item": "^1.2.1",
    "paper-material": "^1.0.6",
    "paper-toggle-button": "^1.2.0",
    "paper-tooltip": "^1.1.3",
    "iron-list": "^1.3.9",
    "iron-flex-layout": "^1.3.1",
    "paper-styles": "^1.1.4"
  }`

**Comment by Chabane** [comment]
Try with 1.0.0-beta.11-webpack.9, it works with angular2-rc7.

1.0.0-beta4 works with angular2-rc6
1.0.0-beta.11-webpack.8 works with angular2-rc5

**Comment by mscharp** [comment]
Thanks for the quick response.

I updated angular-cli to 1.0.0-beta.11-webpack.9 which updated angular to rc7, and left the vaadin script at 1.0.0-beta.4.  I'm still seeing the same error.

I don't have my project laid out the default way the cli set's it up, but if I don't attempt to use the polymerelements anywhere, the angular application works correctly, so I don't think that should matter... though I've been wrong before.

**Comment by mscharp** [comment]
I just went through the angular-cli upgrade process again, and now it's working.  I guess I'll chalk this one up to a bad upgrade the first time.

**Comment by sstorie** [comment]
What about just using vanilla webpack? I'm trying to just get a basic setup working without angular-cli, and I'm running into this same error when I add something like `PolymerElement("paper-button")` to my app module:

> Uncaught Error: Unexpected value 'class0' declared by the module 'AppModule'

As others have reported, once I remove the declaration from the app module the app loads just fine.
