### ISSUE TITLE
Vaadin elements in NPM

### ISSUE THREAD

**Issue by Chabane** [platosha/angular-polymer#91]
Hi,

Is it possible to publish the vaadin elements in NPM? To avoid using bower. Polymer is available in NPM : https://www.npmjs.com/package/@polymer/paper-elements

**Comment by samiheikki** [comment]
Hi @Chabane and thanks for your interest!

We just commented about this in vaadin-date-picker's repo. https://github.com/vaadin/vaadin-date-picker/issues/240

**Comment by Chabane** [comment]
Thanks

I hope that Polymer 2 will be available in NPM

**Comment by Splaktar** [comment]
Not much movement on https://github.com/Polymer/polymer/issues/326 lately, but the Polymer team did say that they were actively working on it in the spring. Perhaps work on Polymer 2.0 is delaying this.
