### ISSUE TITLE
Error: The Polymer element "iron-form" has not been registered.

### ISSUE THREAD

**Issue by bastienlemaitre** [platosha/angular-polymer#92]
Hi, i have many problems with the iron-elements.
With paper-elemets i have no errors, but when i use iron-elements:
- Error: The Polymer element "iron-form" has not been registered. Please check that the element is imported correctly.

Any issues ? Thank you !

**Comment by Chabane** [comment]
Hi,

Have you added iron-form in index.html?

`<link rel="import" href="bower_components/iron-form/iron-form.html"> 
`

And declare it in your module : 

```
@NgModule({
    imports: [],
    declarations: [PolymerElement('iron-form')],
    providers: [],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
```

**Comment by bastienlemaitre** [comment]
Yes i've added it.

**Comment by Saulis** [comment]
Hi!

As `PolymerElement('x-element')` looks for elements named `<x-element>` it doesn't work with Polymer elements that have been extended from native elements like `<form is="iron-form">`.

As a solution in this case I'd suggest using Angular2 form component instead. Another alternative is creating a custom Polymer element that wraps the `<form is="iron-form">`.

For the future, looks like extending native elements will be [dropped in Polymer 2.0](https://github.com/Polymer/polymer/blob/2.0-preview/README.md#v1-custom-elements) so I'm expecting an actual `<iron-form>` element being released at some point.

**Comment by BorntraegerMarc** [comment]
@platosha Should I put this in the docs and close the issue?

**Comment by platosha** [comment]
@BorntraegerMarc yes, please.

In general, it is possible to support extended native elements, but I don’t think this is useful enough. This is going to be dropped in Polymer soon anyway.
