### ISSUE TITLE
Issue regarding build the prod

### ISSUE THREAD

**Issue by ananda121** [platosha/angular-polymer#94]
Hi,
I am using angular 2 gulp and typescript in my project.

Now I want to use Vaadin elements in my project, So I follow this project and add a combobox to my project.
It is running as expected.

But I got error when I try to create a prod-build the project using gulp.

Please anyone help me on this.
Is there any seed project using vaadin which has prod build.

Thanks,
Ananda

**Comment by Chabane** [comment]
Hi @ananda121,

Can you provide the stack trace?

**Comment by ananda121** [comment]
All js and html files from bower_components include in index.html are not found after build run.
Any seed project for gulp project.

**Comment by Splaktar** [comment]
There isn't enough information here. Can you point to a repo with a reproduction? It sounds like there are things that your gulp build is doing wrong or not doing, but it can't be debugged or reviewed without a reproducible example.
