### ISSUE TITLE
iron-list / template example

### ISSUE THREAD

**Issue by alindsay55661** [platosha/angular-polymer#96]
Hi, so this library looks really sweet. While your docs have examples of Vaadin components in action, I couldn't find any examples of google's polymer elements. Right now I am trying to figure out how to deal with things like `*ngFor` and templates. Could you provide the Angular equivalent of this Polymer snippet?

``` html
<iron-list items="[[data]]" as="item">
  <template>
    <div>
      Name: [[item.name]]
    </div>
  </template>
</iron-list>
```

I have successfully imported and rendered the component using the below syntax but there is no data. 

``` html
<iron-list [items]="data" as="item">
  <template>
    <div>
      Name: {{item.value}}
    </div>
  </template>
</iron-list>
```

It looks like the template is getting wiped out by Angular. Any guidance you can provide is greatly appreciated. Also, is the use of `as` correct in this Angular context?

**Comment by JunedS** [comment]
I am too looking for a solution for this.
Shouldnt it be good if Vaadin can provide some examples for all polymer elements? It will make things very clear.

Thanks

**Comment by Saulis** [comment]
Hi!

Unfortunately, the `<template>`, as @alindsay55661 stated, is getting "wiped" by Angular. 
For `<iron-list>`, there currently isn't any workaround available to work with Angular's templating engine.

There's some discussion here: https://github.com/PolymerElements/iron-list/issues/291#issuecomment-251354454

**Comment by platosha** [comment]
One possible workaround is to wrap `<iron-list>` with its template in another Polymer element, that is registered outside Angular templates. For example, create my-list.html:

``` html
<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="bower_components/iron-list/iron-list.html">

<dom-module id="my-list">
  <template>
    <iron-list items="[[items]]" as="item">
      <template>
        <div>
          Name: [[item.name]]
        </div>
      </template>
    </iron-list>
  </template>

  <script>
    Polymer({
      is: "my-list",
      properties: {
        items: Array
      }
    });
  </script>
</dom-module>
```

Then import it in index.html, just like any other Polymer element:

``` html
...
  <head>
    ...
    <link rel="import" href="my-list.html">
  </head>
...
```

Then you can use the `<my-list>` element in declarations (`PolymerElement('my-list')`), as well as in Angular templates. The `<iron-list>` template was already defined in `<my-list>`, therefore we don't have it in Angular templates:

``` html
<my-list [items]="data"></my-list>
```

It requires a bit of work, though: you have to manually bypass all the properties and methods you use in `<iron-list>` through `<my-list>`. In the example above, only the `items` property is bypassed.

**Comment by BorntraegerMarc** [comment]
@platosha Should I put this in the docs and close this issue?

**Comment by platosha** [comment]
@BorntraegerMarc yes.
