### ISSUE TITLE
add polymer

### ISSUE THREAD

**Issue by elvisbegovic** [platosha/angular-polymer#97]
ENHANCEMENT

I just try to add polymerelement into my angular-cli beta16 project and it's so hard, I except from 3th party lib to inject it into declaration : [] that's all, I think  actually isn't easy to add polametelement into ng2 app, 

Why it's so complicate? We different angular2 configuration (of course your's different) I try to add polymer-element into my angular-cli project and I don't understand how proceed even with https://vaadin.com/docs/-/part/elements/angular2-polymer/ng-cli.html

i wonder if it's updated and what I really need

**Comment by cschroeter** [comment]
To use Polymer components you have to use Bower. There are packages available on NPM but they are outdated. This leads to the fact that you have to include another package manager into your project.

Polymer is build on top of webcomponents. Not all major browsers supporting those new APIs. Thats why you have to add polyfills and delay the bootstrap until those polyfills have been loaded.

That are the minimum requirements and I don't see any kind of enhancement.

**Comment by samiheikki** [comment]
Hey @istiti 

As @cschroeter mentioned Polymer elements uses Bower and in an npm powered framework, it requires some extra work. Polymer team is currently working on serving their elements in npm with yarn. When this happens, we'll surely simplify the process for using Polymer elements in Angular 2.

But right now, we are unable to simplify it.
